import { number } from "yup";
import { PageSearchRequestModel } from "../configuration/PageRequestModel";

export class AcquiringTransactionFilterModel extends PageSearchRequestModel {
  cardNumber!: string;
  institutionId!: string;
  merchantTransactionId!: number;
  outletId!: string;
  terminalId!: string;
  transactionId!: string;
  manualEntry!: string;
  settlMerchHalt!: string;
  fromProcessingDate!: Date | null;
  toProcessingDate!: Date | null;
  authorizationNumber!: string;
  batchId!: string;
  merchantName!: string;
  merchantAccountNumber!: string;
}

export class AcquiringTransactionModel {
  acquiringTransactionId!: number;
  institutionId!: string;
  institutionName!: string;
  transactionCurrencyId!: number;
  transactionCurrencyCode!: string;
  transactionCurrencyName!: string;
  entitiesId!: string;
  entityName!: string;
  terminalId!: number;
  manualEntry!: string;
  processingDate!: Date;
  cardNumber!: string;
  merchantName!: string;
  transactionId!: string;
  transactionDescription!: string;
  transactionDate!: string;
  transactionAmount!: number;
  authorizationCode!: string;
  settlementAmount!: number;
  microfilmRefNbr!: string;
  refNumberSequence!: number;
  pan!: string;
  cardSchemeId!: string;
  cardSchemeName!: string;
  linkupCode!: string;
  processingCode!: number;
  reversal!: string;
  billingAmount!: number;
  billingCurrencyId!: number;
  billingCurrencyCode!: string;
  billingCurrencyName!: string;
  localAmount!: number;
  localCurrencyId!: number;
  localCurrencyCode!: string;
  localCurrencyName!: string;
  tipsAmount!: number;
  tipsCurrencyId!: number;
  tipsCurrencyCode!: string;
  tipsCurrencyName!: string;
  dccAmount!: number;
  dccCurrencyId!: number;
  dccCurrencyCode!: string;
  dccCurrencyName!: string;
  dccMerchantAmount!: number;
  dccMerchantSettlAmount!: number;
  dccMerchantSettlAmountCurrencyId!: number;
  dccMerchantSettlAmountCurrencyCode!: string;
  dccMerchantSettlAmountCurrencyName!: string;
  merchantCommisionNumber!: number;
  merchantMarkUpNumber!: number;
  chMarkUpNumber!: number;
  feeAmount1!: number;
  feeAmount1CurrencyId!: number;
  feeAmount1CurrencyCode!: string;
  feeAmount1CurrencyName!: string;
  feeAmount2!: number;
  feeAmount2CurrencyId!: number;
  feeAmount2CurrencyCode!: string;
  feeAmount2CurrencyName!: string;
  transactionTime!: Date;
  maskPan!: string;
  billingProcessingFlag!: string;
  settlProcessingFlag!: string;
  settlProcessingNbr!: number;
  settlMerchHalt!: string;
  merchantCountry!: string;
  acquirerId!: string;
  issuerId!: number;
  issuerProfile!: string;
  issueDescription!: string;
  issuerRefNum!: string;
  outletCode!: string;
  merchantAccountNumber!: string;
  merchantAccountCurrId!: number;
  merchantAccountCurrCode!: string;
  merchantAccountCurrName!: string;
  merchantCategory!: string;
  terminalLocation!: string;
  acquirerData!: string;
  issuerData!: string;
  terminalData!: string;
  eCommerceFlag!: string;
  originNetwork!: string;
  destinationNetwork!: string;
  merchantSettlDate!: Date;
  merchantPaymentDate!: Date
  settlementCurrencyId!: number;
  settlementCurrencyCode!: string;
  settlementCurrencyName!: string;
  reversalReason!: string;
  reversalComment!: string;
  manualComment!: string;
  chergebackReason!: string;
  chargebackComment!: string;
  payHaltComment!: string;
  accquierRecordToAppear!: string;
  issueRecordToAppear!: string;
  processingRefNbr1!: string;
  processingRefNbr2!: string;
  processingRefNbr3!: string;
  processingRefNbr4!: string;
  processingRefNbr5!: string;
  representmentReason!: string;
  representmentComment!: string;
  toBePaidToMerchant!: string;
  usageCode!: number;
  payHaltStatus!: string;
  confirmStoppingPayment!: string;
  pageNo!: string;
  pageSize!: string;
  systemCodeId!: number;
  codeSuffix!: string;
  codePrefix!: string;
  codePattern!: string;
  codeValue!: string;
  codeDescription!: string;
  merchantBank!: string;
  merchantIban!: string;
}

export class HaltResponse{
  acquiringTransactionModel!:AcquiringTransactionModel;
  errorMessages!:string[];
}

export class TransactionCurrentModel {
  recordSeqId!: number;
  institutionId!: string;
  outletCode!: string;
  merchantName!: string;
  merchantCategory!: string;
  merchantBank!: string;
  merchantAccountNumber!: string;
  merchantIBAN!: string;
  merchantAccountCurrency!: string;
  merchantBranch!: string;
  merchantBankSwift!: string;
  merchantBeneficiaryName!: string;
  merchPaymentDate!: Date;
  terminalId!: number;
  terminalLocation!: string;
  sourceReference!: string;
  pan!: string;
  cardNumber!: string;
  maskPan!: string;
  cardSeqNumber!: number;
  expiryDate!: string;
  microfilmRefNumber!: string;
  refNumberSeq!: number;
  issuerAcqProfile!: string;
  cardScheme!: string;
  linkupCode!: string;
  processingCode!: number;
  transId!: string;
  reversalFlag!: string;
  sourceAmount!: number;
  sourceCurrency!: string;
  billingAmount!: number;
  billingCurrency!: string;
  settlementAmount!: number;
  settlementCurrency!: string;
  localAmount!: number;
  localCurrency!: string;
  tipsAmount!: number;
  tipsSettlementAmount!: number;
  tipsCurrency!: string;
  dccAmount!: number;
  dccCurrency!: string;
  dccMerchantAmount!: number;
  dccMerchantSettlementAmount!: number;
  dccMerchantSettlementCurrency!: string;
  merchantCommission!: number;
  merchMarkup!: number;
  chMarkup!: number;
  feeAmount1!: number;
  feeAmount1Currency!: string;
  feeAmount2!: number;
  feeAmount2Currency!: string;
  transactionAmount!: number;
  transCurrency!: string;
  transactionDate!: string;
  transTime!: string;
  authorizationNumber!: string;
  billingProcessingFlag!: string;
  settlProcessingFlag!: string;
  settlProcessingNumber!: number;
  settlMerchHalt!: string;
  batchId!: string;
  merchantCountry!: string;
  acquirerId!: string;
  issuerId!: string;
  issuerRefNumber!: string;
  acqInstId!: string;
  issuerInstId!: string;
  acquirerData!: string;
  issuerData!: string;
  terminalData!: string;
  ecommerceFlag!: string;
  originNetwork!: string;
  destinationNetwork!: string;
  processingDate!: string;
  merchSettlementDate!: string;
  reversalReason!: string;
  reversalComment!: string;
  manualEntry!: string;
  manualComment!: string;
  chargebackComment!: string;
  chargebackReason!: string;
  representmentComment!: string;
  representmentReason!: string;
  confirmStoppingPayment!: string;
  toBePaidToMerchant!: string;
  payHaltComment!: string;
  payHaltStatus!: string;
  usageCode!: number;
  reasonCode!: number;
  acquirerRecordToAppear!: string;
  issuerRecordToAppear!: string;
  processingRefNumber1!: string;
  processingRefNumber2!: string;
  processingRefNumber3!: string;
  processingRefNumber4!: string;
  processingRefNumber5!: string;
  userCreate!: string;
  dateCreate!: string;
}

export class HaltPayModel {
  acquiringTransactionId!: number;
  payHaltComment!: string;
  payHaltStatus!: string;
  confirmStoppingPayment!: string;
  institutionId!: string;
}

export class UnhaltPayModel {
  institutionId!: string;
  acquiringTransactionIds!: number[];
}

export class RepresentmentModel {
  accquierRecordToAppear!: string;
  acquiringTransactionId!: number;
  chargebackComment!: string;
  systemCodeId!: number;
  settlMerchHalt!: string;
  institutionId!: string;
}

export class ReversalTransactionModel {
  accquierRecordToAppear!: string;
  acquiringTransactionId!: number;
  institutionId!: string;
  reversalComment!: string;
  systemCodeId!: number;
}